### ISSUE TITLE
Proper operation of iterator

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-node#2]
The current `getNodeIterator` implementation is broken: https://github.com/digitalbazaar/bedrock-ledger-node/blob/cm4/lib/index.js#L477

It works fine as long as all the ledgers are public and/or the actor has admin permissions.  However, when the actor is a regular user, and there are ledger nodes owned by other identities, the problems arise.

The fundamental issue is that the query is returning nodes that the actor may not have permissions to access.  I believe this was done because although an actor may not be the owner of a node, the owner may be an organization that the actor belongs to, but I don't think we've developed a mechanism to query for resources that an actor has permissions to access.  Prior to introducing organizations, it was just a matter of querying based on the `owner` of a resource.

The issues that need to be addressed:
1. The API reports that there is a `next` node to be had, when in fact the user may not have permission to access that node.
2. Presently, the first time `api.get` encounters a `PermissionDenied` error, the iterator stops cold.  Depending on how #1 is addressed, this routine should fast forward through the cursor until it finds a valid node.

**Comment by dlongley** [comment]
Note that #6 shouldn't close this issue out, it just partially addresses it. Namely, it addresses a correctness issue. It likely introduces a significant performance issue though -- that we still need to address with a more efficient implementation.

**Comment by mattcollier** [comment]
Created new issue to track performance https://github.com/digitalbazaar/bedrock-ledger-node/issues/7
