### ISSUE TITLE
Refactor validation

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-node#26]
We have commit that requires passing the `ledgerNode` into the validation API.

Since this is the case, all of the logic found here can be pushed into the validator itself:
https://github.com/digitalbazaar/bedrock-ledger-node/blame/master/lib/ledger-node-operations.js#L55

This will greatly simplify the `validate` API signature here: https://github.com/digitalbazaar/bedrock-ledger-node/blame/master/lib/validator.js#L13

Signature would likely be:
```
validate({input, ledgerNode}, callback);
```

It is very good that validators are being given `ledgerNode` because they may need to determine latest blockHeight etc.

**Comment by dlongley** [comment]
+1 for simplifying validator API and bringing inline with our other named param APIs + prepping for move to promises.

**Comment by dlongley** [comment]
This should wait until the promises PR (not submitted yet, but WIP) is merged in.
