### ISSUE TITLE
Improve performance of basisBlockHeight computation of incoming operations

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-node#63]
We need to add `basisBlockHeight` to every incoming operation.  Currently we are hitting Mongo on every operation.  Is there a better way?

https://github.com/digitalbazaar/bedrock-ledger-node/blob/master/lib/LedgerNodeOperations.js#L36-L37

**Comment by dlongley** [comment]
In memory LRU cache + block event handler to update it?

**Comment by mattcollier** [comment]
I get that we would have an in-memory variable that is initialized on `bedrock.start` and updated on `bedrock-ledger-storage.block.add`.  It's not clear to me where the LRU part comes in.  That implies to me that this variable (cache) would be invalidated at some interval?

https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/LedgerBlockStorage.js#L123

https://github.com/isaacs/node-lru-cache
