### ISSUE TITLE
Validator for @context is to strict

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-node#64]
The validator for the contexts will accept the following:

```
 properties: {
   41         '@context': {
   42           anyOf: [
   43             schemas.url(), {
   44               type: 'array',
   45               minItems: 1,
   46               items: schemas.url(),
   47             }
   48           ]
   49         },
```

However a context can be a piece of json-ld itself hence passing in a context that does not need to be dereferenced using a documentLoader results in an error.

Steps:

1. Create a record for a web ledger operation.
2. set @context to a json object that is a valid json-ld context.
3. create a WebLedgerRecords operation
4. watch things blow up in your logger.

**Comment by dlongley** [comment]
Embedded contexts are not presently permitted in WebLedger operations (and we probably don't want to loosen that restriction). Just because something is valid JSON-LD doesn't mean it conforms to a more restricted profile for WebLedger.

**Comment by dlongley** [comment]
@mattcollier -- if you agree, we should close this as not a bug but a design choice.

**Comment by aljones15** [comment]
@davidlehn also agrees with this so closing. I just extended the documentLoader in the project.
