### ISSUE TITLE
Remove usage of bedrock-identity

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-node#84]

**Comment by aljones15** [comment]
what is the remaining usage of `bedrock-identity` in this module?

**Comment by dlongley** [comment]
@aljones15, the tests use it instead of bedrock-account for various calls.

**Comment by aljones15** [comment]
Just in case anyone ends up with this issue:

https://github.com/digitalbazaar/bedrock-ledger-node/blob/mongo-version-3/test/package.json

The `bedrock-identity` then needs to be removed from the tests:

```
        actor = await brIdentity.getCapabilities({id});
```
that should be replaced with

```
brAccount.getCapabilities
```

you can see an example here:

https://github.com/digitalbazaar/bedrock-ledger-agent/blob/c620509aea5d82d684b63400492688290af9e110/test/mocha/10-agent-api.js#L28-L32
